#pragma once

typedef enum _CGSS_FILE_MODE {
    CGSS_FILE_MODE_NONE = 0,
    CGSS_FILE_MODE_APPEND = 1,
    CGSS_FILE_MODE_CREATE = 2,
    CGSS_FILE_MODE_CREATE_NEW = 3,
    CGSS_FILE_MODE_OPEN_EXISTING = 4,
    CGSS_FILE_MODE_OPEN_OR_CREATE = 5,
    _CGSS_FILE_MODE_FORCE_DWORD = 0x7fffffff,
} CGSS_FILE_MODE;
