#pragma once

typedef enum _CGSS_UTF_COLUMN_TYPE {
    CGSS_UTF_COLUMN_TYPE_U8 = 0,
    CGSS_UTF_COLUMN_TYPE_S8 = 1,
    CGSS_UTF_COLUMN_TYPE_U16 = 2,
    CGSS_UTF_COLUMN_TYPE_S16 = 3,
    CGSS_UTF_COLUMN_TYPE_U32 = 4,
    CGSS_UTF_COLUMN_TYPE_S32 = 5,
    CGSS_UTF_COLUMN_TYPE_U64 = 6,
    CGSS_UTF_COLUMN_TYPE_S64 = 7,
    CGSS_UTF_COLUMN_TYPE_R32 = 8,
    CGSS_UTF_COLUMN_TYPE_R64 = 9,
    CGSS_UTF_COLUMN_TYPE_STRING = 10,
    CGSS_UTF_COLUMN_TYPE_DATA = 11,
    CGSS_UTF_COLUMN_TYPE_MASK = 0x0f,
} CGSS_UTF_COLUMN_TYPE;
