#pragma once

typedef enum _CGSS_UTF_COLUMN_STORAGE {
    CGSS_UTF_COLUMN_STORAGE_ZERO = 0x10,
    CGSS_UTF_COLUMN_STORAGE_CONST = 0x30,
    CGSS_UTF_COLUMN_STORAGE_PER_ROW = 0x50,
    CGSS_UTF_COLUMN_STORAGE_CONST2 = 0x70,
    CGSS_UTF_COLUMN_STORAGE_MASK = 0xf0,
} CGSS_UTF_COLUMN_STORAGE;
