#pragma once

typedef enum _CGSS_FILE_ACCESS {
    CGSS_FILE_ACCESS_NONE = 0,
    CGSS_FILE_ACCESS_READ = 1,
    CGSS_FILE_ACCESS_WRITE = 2,
    CGSS_FILE_ACCESS_READ_WRITE = 3,
    _CGSS_FILE_ACCESS_FORCE_DWORD = 0x7fffffff,
} CGSS_FILE_ACCESS;
