#pragma once

typedef enum _CGSS_ACB_WAVEFORM_ENCODE_TYPE {
    CGSS_ACB_WAVEFORM_ADX = 0,
    CGSS_ACB_WAVEFORM_HCA = 2,
    CGSS_ACB_WAVEFORM_HCA2 = 6,
    CGSS_ACB_WAVEFORM_VAG = 7,
    CGSS_ACB_WAVEFORM_ATRAC3 = 8,
    CGSS_ACB_WAVEFORM_BCWAV = 9,
    CGSS_ACB_WAVEFORM_NINTENDO_DSP = 13,
} CGSS_ACB_WAVEFORM_ENCODE_TYPE;
