add_executable(hcacc ${HCACC_SOURCE_FILES})
add_executable(hcaenc_obsolete ${HCAENC_SOURCE_FILES})
add_executable(hca2wav ${HCA2WAV_SOURCE_FILES})
add_executable(hcainfo ${HCAINFO_SOURCE_FILES})
add_executable(utftable ${UTFTABLE_SOURCE_FILES})
add_executable(acbunpack ${ACBUNPACK_SOURCE_FILES})
add_executable(acb2wavs ${ACB2WAVS_SOURCE_FILES})
add_executable(acb2hcas ${ACB2HCAS_SOURCE_FILES})
add_library(cgss SHARED ${LIBCGSS_SOURCE_FILES})
